### ISSUE TITLE
model generator

### ISSUE THREAD

**Issue by ramigg** [azanium/generator-astro#11]
nice project! 
It would be great to add a model generator.

thanks!

**Comment by azacode** [comment]
The model generator is there using Sequelize (if you use it). That is the reason I didn't add any model generator, to make it independent of any ORM. 

One example to generate the model:

`$ sequelize model:generate --name PasswordGrantCode --attributes id:string,grantId:uuidv4,userCode:uuidv4,data:json,expiresAt:date,consumedAt:date
`

But you need to install sequelize-cli for this to work.

**Comment by azapedia** [comment]
This no longer an issue

**Comment by azanium** [comment]
Closing this
