### ISSUE TITLE
Readme issue

### ISSUE THREAD

**Issue by balvinder294** [azanium/generator-astro#3]
Hey there we are using this one for api in our projects, the issue is that whenever we generate the project. The generated readme does not contain how to add api , services, etc. but shows some boilerplate copying block. Maybe this is misconfigured or by any way, just wanted to share this one issue.
As new devs work on this, they have no idea how to to do things with this else running.

**Comment by azanium** [comment]
Can you elaborate, what kind of README being generated instead? If you can paste it here the excerpt.
I will fix it if it's related to the generator.

**Comment by balvinder294** [comment]
Hey , this one block
## Getting Started

Clone the repo and make it yours:

```bash
git clone --depth 1 https://github.com/danielfsousa/express-rest-es2017-boilerplate
cd express-rest-es2017-boilerplate
rm -rf .git
```

Install dependencies:

```bash
yarn
```

Set environment variables:

```bash
cp .env.example .env
```

I have manually added this one from generator readme

Generate a new api:

```
yo astro:api
```

Generate a new middleware:

```
yo astro:middleware
```

Generate a new service:

```
yo astro:service
```

Generate a new utility:

```
yo astro:util
```

Generate a new boot task:

```
yo astro:boot
```

This way new devs can easily know how to do things , and thanks for responding.

**Comment by azanium** [comment]
I've simplified things on the README, also you don't need to copy .env.example manually, it's done automatically first time you generate new project.

Thanks

**Comment by balvinder294** [comment]
Hehe thanks, and I was saying I added the below lines, not the environment, keep maintaining...
