### ISSUE TITLE
Issue with Nodemon

### ISSUE THREAD

**Issue by khanna91** [azanium/generator-astro#9]
Hello,

Since I upgraded to latest major version of generator, facing issue with nodemon. Seems it doesn't kill the previous instance, before restarting the new one.

Maybe, because now server startup is not a part of index.js itself and is moved as a boot process??

Does anyone face the same issue? 

Thanks.

**Comment by azanium** [comment]
I have retested using v4.0.9, and use 
```
yarn dev
```

And add a couple apis, modify them, save, everyting seems to be working fine.

Can you elaborate more, on how to reproduce the issue?

**Comment by azanium** [comment]
I think this issue not related to the generator, but most likely with your local nodemon
